/**
 * Stable, documented error codes returned in the public error envelope.
 * Adding codes is backwards compatible; renaming or removing them is not.
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALFORMED_JSON: 'MALFORMED_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  CSRF_INVALID: 'CSRF_INVALID',
  ORIGIN_NOT_ALLOWED: 'ORIGIN_NOT_ALLOWED',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  FINDING_NOT_FOUND: 'FINDING_NOT_FOUND',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_VERSION_CONFLICT: 'DOCUMENT_VERSION_CONFLICT',
  REVIEW_NOT_COMPLETED: 'REVIEW_NOT_COMPLETED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  CONFLICT: 'CONFLICT',
  LLM_SERVICE_UNAVAILABLE: 'LLM_SERVICE_UNAVAILABLE',
  LLM_SERVICE_TIMEOUT: 'LLM_SERVICE_TIMEOUT',
  LLM_SERVICE_RATE_LIMITED: 'LLM_SERVICE_RATE_LIMITED',
  LLM_INVALID_RESPONSE: 'LLM_INVALID_RESPONSE',
  LLM_REQUEST_REJECTED: 'LLM_REQUEST_REJECTED',
  PROCESSING_TIMEOUT: 'PROCESSING_TIMEOUT',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
